user_1 = User.find_or_create_by!(name: "John Doe")
user_2 = User.find_or_create_by!(name: "Jane Doe")
project=Project.find_or_create_by!(name: "Sample Project", status: 'open')
project.users << user_1 unless project.users.include?(user_1)
project.users << user_2 unless project.users.include?(user_2)
